# Generated by Django 3.2.5 on 2021-07-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioMarcado',
            fields=[
                ('horario', models.DateTimeField(primary_key=True, serialize=False)),
                ('matricula', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Horario',
            new_name='HorarioLivre',
        ),
    ]
