# Generated by Django 3.2.5 on 2021-07-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0002_auto_20210712_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariolivre',
            options={'verbose_name': 'Horário livre', 'verbose_name_plural': 'Horários livres'},
        ),
        migrations.AlterModelOptions(
            name='horariomarcado',
            options={'verbose_name': 'Horário marcado', 'verbose_name_plural': 'Horários marcados'},
        ),
        migrations.AddField(
            model_name='horariomarcado',
            name='email',
            field=models.EmailField(default='null@null.com', max_length=254),
        ),
    ]
