# Generated by Django 3.2.5 on 2021-07-16 00:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0003_auto_20210712_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariomarcado',
            name='id',
            field=models.BigAutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horariolivre',
            name='horario',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 16, 0, 3, 45, 240757, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='horariomarcado',
            name='horario',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
