# Generated by Django 3.2.5 on 2021-08-16 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0004_auto_20210715_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='horariolivre',
            name='horario',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 16, 19, 59, 45, 174716, tzinfo=utc), null=True),
        ),
    ]
